In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
def get_data(x,y,z):
    gw1 = pd.read_csv(f"/Users/pryke/Documents/Projects/Fantasy football/Data/{x}.csv")
    gw2 = pd.read_csv(f"/Users/pryke/Documents/Projects/Fantasy football/Data/{y}.csv")
    gw3 = pd.read_csv(f"/Users/pryke/Documents/Projects/Fantasy football/Data/{z}.csv")
    teams = pd.read_csv(f"/Users/pryke/Documents/Projects/Fantasy football/Data/teams.csv")

In [ ]:
get_data(gw1,gw2,gw3)

In [ ]:
teams.rename(columns= {'id':'opponent_team','name':'opponent_team_name'}, inplace= True)

In [45]:
week = 1

for x in [gw1,gw2,gw3]:
    x['round'] = week
    x.drop(labels = ['xP','fixture','selected','team_a_score','team_h_score','transfers_balance','transfers_in','transfers_out'],axis=1,inplace=True)
    week+=1
    
gw1 = gw1.merge(teams,on='opponent_team')
gw2 = gw2.merge(teams,on='opponent_team')
gw3 = gw3.merge(teams,on='opponent_team')

In [46]:
data = gw1.append(other = gw2, ignore_index=True)
data = data.append(other = gw3, ignore_index=True)

In [51]:
data.columns

Index(['name', 'position', 'team', 'assists', 'bonus', 'bps', 'clean_sheets',
       'creativity', 'element', 'goals_conceded', 'goals_scored', 'ict_index',
       'influence', 'kickoff_time', 'minutes', 'opponent_team', 'own_goals',
       'penalties_missed', 'penalties_saved', 'red_cards', 'round', 'saves',
       'threat', 'total_points', 'value', 'was_home', 'yellow_cards',
       'opponent_team_name', 'elo'],
      dtype='object')

In [68]:
data1 = round(data.groupby('name').mean(),3)

In [69]:
data1

,assists,bonus,bps,clean_sheets,creativity,element,goals_conceded,goals_scored,ict_index,influence,...,penalties_saved,red_cards,round,saves,threat,total_points,value,was_home,yellow_cards,elo
name,,,,,,,,,,,,,,,,,,,,,
Aaron Connolly,0.000,0.000,-0.667,0.000,0.367,72.0,0.000,0.000,0.167,0.000,...,0.0,0.0,2.0,0.0,2.000,0.333,55.000,0.667,0.000,1655.667
Aaron Cresswell,0.333,0.333,22.667,0.000,12.967,411.0,1.667,0.333,4.967,28.200,...,0.0,0.0,2.0,0.0,8.667,4.667,55.000,0.667,0.000,1763.667
Aaron Lennon,0.000,0.000,-2.000,0.000,0.500,575.0,1.000,0.000,0.500,4.600,...,0.0,0.0,3.0,0.0,0.000,0.000,50.000,1.000,1.000,1703.000
Aaron Ramsdale,0.000,0.000,0.000,0.000,0.000,559.0,0.000,0.000,0.000,0.000,...,0.0,0.0,2.5,0.0,0.000,0.000,45.000,0.500,0.000,1962.000
Aaron Ramsey,0.000,0.000,0.000,0.000,0.000,496.0,0.000,0.000,0.000,0.000,...,0.0,0.0,2.0,0.0,0.000,0.000,45.000,0.667,0.000,1685.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Youri Tielemans,0.000,0.000,21.000,0.333,12.533,210.0,1.667,0.333,6.000,32.333,...,0.0,0.0,2.0,0.0,15.000,4.000,65.000,0.333,0.000,1694.667
Yves Bissouma,0.333,0.667,18.333,0.333,7.400,70.0,1.000,0.000,3.167,19.000,...,0.0,0.0,2.0,0.0,5.000,3.667,45.333,0.667,0.333,1655.667
Zack Steffen,0.000,0.000,0.000,0.000,0.000,260.0,0.000,0.000,0.000,0.000,...,0.0,0.0,2.0,0.0,0.000,0.000,45.000,0.667,0.000,1765.000
Álvaro Fernández,0.000,0.000,0.000,0.000,0.000,556.0,0.000,0.000,0.000,0.000,...,0.0,0.0,2.5,0.0,0.000,0.000,45.000,0.000,0.000,1747.500
Çaglar Söyüncü,0.000,0.000,16.333,0.333,0.433,217.0,1.667,0.000,2.133,20.733,...,0.0,0.0,2.0,0.0,0.000,2.667,50.000,0.333,0.000,1694.667